### PR TITLE
1º Milestone | Image Entity DB

### PR DESCRIPTION
**Pull request by Maclenn77**
Hi! I created a new pull request because [the previous one](https://github.com/microverseinc/ror-social-scaffold/pull/95) it was done from phfdonda/development to microverseinc/master, instead of from feature to development.

We solved the previous problems. 

- Create a docs directory
- Add image_link in the user's table

Greetings, and thanks for reviewing!

### CODE REVIEW

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team      
#### Great Job so far, but there are a few more things required. 
### General
- [x] Let's include linter for this project
- [x] For the `Friendship` table lets change `user` to `user_id` and `friend` to `friend_id`
- [x] Add primary key `PK` to `Likes`,`Comments` & `Posts`
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by phfdonda** [comment]
Hi, @kobiyoyo! Thank you for your review! Yeah, it makes sense, to point that the keys are foreign keys, right? We have changed what you requested, and also added the project to Stickler.
Have a great weekend!

**Review by Forison — CHANGES_REQUESTED** [review]
## Status::Require change❌
## 🙋‍♂️ Team!!!
#### Good job on addressing the issue raised with the ERD.
Your linters checks were failing I was surprised since at this stage there should not be any real coding, but I realized that you have started implementation. since you have some coding going on already I can not approve the project until the cheeks pass🥶 .
## That is it, address the issue with the linter and submit another code review😎.
#### Happy coding👨‍💻
Addo Forison

**Comment by phfdonda** [comment]
Hi, thanks for the review. Yeah, we got ahead of ourselves! Haha
Fixed!

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team      
#### Great Job so far, but there is one more thing to address, the stickler errors.
- [x] Let's take a step back and address each issue one by one
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by phfdonda** [comment]
Fixed.

**Review by mosesogwo — APPROVED** [review]
**Hello! Milestone is approved:stars:**

- Please note that your branch name does not reflect the feature for this milestone. Keep each feature within it's branch.

**Good luck**

### Status: Approved! :heavy_check_mark:

**Pull request merged**
